# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ade09b46-79c2-4657-b712-24004059df6c'
  imageRepository: 'flyingdutchmanproofofconceptbg'
  containerRegistry: 'myacrwebapp.azurecr.io'
  dockerfilePathCa: '$(Build.SourcesDirectory)/calc-engine/Dockerfile'
  dockerfilePathFe: '$(Build.SourcesDirectory)/dash-fe/Dockerfile'
  dockerfilePathGr: '$(Build.SourcesDirectory)/graphql/Dockerfile'
  dockerfilePathSe: '$(Build.SourcesDirectory)/graphql/Dockerfile'
  tag: '$(Build.BuildId)-$(System.TeamProject)-$(Build.SourceBranchName)-$(component)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool: mycomputeragent
    variables:
      component: 'Ca'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePathCa)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - script: echo "The $(component) component has been built."
    - job: Build
      displayName: Build
      pool: mycomputeragent
      variables:
        component: 'Fe'
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePathFe)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)
      - script: echo "The $(component) component has been built."
    - job: Build
      displayName: Build
      pool: mycomputeragent
      variables:
        component: 'Gr'
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePathGr)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)
      - script: echo "The $(component) component has been built."
    - job: Build
      displayName: Build
      pool: mycomputeragent
      variables:
        component: 'Se'
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePathSe)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)
      - script: echo "The $(component) component has been built."