version: '3'

services:
  storage-engine:
    build: ./storage-engine
    networks:
      my-network:
        ipv4_address: 172.20.0.2

  calc-engine:
    build: ./calc-engine
    networks:
      my-network:
        ipv4_address: 172.20.0.3
    depends_on:
      - storage-engine

  graphql:
    build: ./graphql
    networks:
      my-network:
        ipv4_address: 172.20.0.4
    depends_on:
      - calc-engine

  dash-fe:
    build: ./dash-fe
    networks:
      my-network:
        ipv4_address: 172.20.0.5
    ports:
      - "8050:8050"
    depends_on:
      - graphql

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1