apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: http
      port: 8050
      targetPort: 8050
    - name: http-1
      port: 5020
      targetPort: 5020

  type: LoadBalancer

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: graphql-service
# spec:
#   selector:
#     app: graphql
#   ports:
#     - name: http
#       port: 5020
#       targetPort: 5020

---
apiVersion: v1
kind: Service
metadata:
  name: calc-engine-service
spec:
  selector:
    app: calc-engine
  ports:
    - name: http
      port: 5015
      targetPort: 5015

---
apiVersion: v1
kind: Service
metadata:
  name: storage-engine-service
spec:
  selector:
    app: storage-engine
  ports:
    - name: http
      port: 5006
      targetPort: 5006